import dotenv
import os

dotenv.load_dotenv()


OPENAI_API_KEY = os.environ['OPENAI_API_KEY']
OPENAI_MODEL_NAME = os.environ['OPENAI_MODEL_NAME']
OPENAI_MODEL_TEMPERATURE = float(os.environ['OPENAI_MODEL_TEMPERATURE'])
RAW_DATA_FOLDER_NAME = os.environ['RAW_DATA_FOLDERNAME']
RAW_DATA_FILENAME = os.environ['RAW_DATA_FILENAME']
VECTORDB_COLLECTION_NAME = os.environ['VECTORDB_COLLECTION_NAME']
VECTORDB_PERSIST_FOLDERNAME = os.environ['VECTORDB_PERSIST_FOLDERNAME']
NUMBER_OF_SIMILARITY_RESULTS = int(os.environ['NUMBER_OF_SIMILARITY_RESULTS'])
AI_IMAGES_SAVE_DIRECTORY = os.environ['AI_IMAGES_SAVE_DIRECTORY']
IMAGE_WIDTH = int(os.environ['IMAGE_WIDTH'])
IMAGE_HEIGHT = int(os.environ['IMAGE_HEIGHT'])
STABILITY_API_KEY = os.environ['STABILITY_API_KEY']
IMAGE_ENGINE = os.environ['IMAGE_ENGINE']
INSTAGRAM_USERNAME = os.environ['INSTAGRAM_USERNAME']
INSTAGRAM_PASSWORD = os.environ['INSTAGRAM_PASSWORD']
